### ISSUE TITLE
Serial Number on Boundary

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#106]
I believe that the SN of a candidate should change if it crosses some boundary. We translate its source position in that case > it is not more the same source as before > it should have a new SN also.

Test example:

``` python
from crpropa import *

c = Candidate()
c.current.setPosition(Vector3d(1, 1, 1))
c.current.setDirection(Vector3d(-1, 0, 0))

prop = SimplePropagation(2, 2)
boundary = ReflectiveBox(Vector3d(0,0,0), Vector3d(2,2,2))
for i in xrange(2):
    prop.process(c)
    boundary.process(c)
    print "In step {}. position is {} with SN {}".format(i+1, c.current.getPosition(), c.getSerialNumber())
```

Will something like this work at the end of the process method for every boundary condition?

``` cpp
...
c->setNextSerialNumber(c->getNextSerialNumber());
```

**Comment by DavidWalz** [comment]
Hey Andrej,
Do you have a use case that would benefit from this behavior?
Probably the main reason for serial numbers is to easily identify which secondary particles are related. This is lost when we assign new serial numbers. However, if one does want to have this behavior one can still make an additional comparison of source.position.
One the other hand, assigning new serial number is not unproblematic because if a particle traverses a boundary twice (there and back) it should get his old serial number back.

**Comment by adundovi** [comment]
The main reason would be to easily select an event in a case of multiple detections of the same particle (e.g. the magnetized observer issue) - we just allow events with a unique SN. Crossing boundary creates a new particle from the perspective of the observer.

About the identification of secondary particles - I thought that this is not crucial because those secondaries could originate from some other, undetected primary. Maybe this is important only in a limit of low statistics, or am I missing something?

Though I agree with the second argument - we could end up in saving infinite number of SN for each particle. Due to that, I will put this idea on hold and think more about it.
