### ISSUE TITLE
Apparent syntax error in PshirkovField.h

### ISSUE THREAD

**Issue by antiantimatter** [CRPropa/CRPropa3#109]
Running make:

[ 84%] Generating crpropa_wrap.cxx
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:172: Warning 361: operator! ignored
/home/HP/CRPropa3-master/include/crpropa/module/PropagationCK.h:46: Warning 325: Nested class not currently supported (Y ignored)
/home/HP/CRPropa3-master/include/crpropa/module/ParticleCollector.h:29: Warning 389: operator[] ignored (consider using %extend)
/home/HP/CRPropa3-master/include/crpropa/Source.h:365: Warning 325: Nested struct not currently supported (Nucleus ignored)
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:168: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/home/HP/CRPropa3-master/include/crpropa/Grid.h:123: Warning 508: previous declaration of 'get'.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:168: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/home/HP/CRPropa3-master/include/crpropa/Grid.h:128: Warning 508: previous declaration of 'get'.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:168: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/home/HP/CRPropa3-master/include/crpropa/Grid.h:123: Warning 508: previous declaration of 'get'.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:168: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/home/HP/CRPropa3-master/include/crpropa/Grid.h:128: Warning 508: previous declaration of 'get'.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:158: Warning 503: Can't wrap 'operator crpropa::Grid< crpropa::Vector3< float > >*' unless renamed to a valid identifier.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:158: Warning 503: Can't wrap 'operator crpropa::Grid< float >*' unless renamed to a valid identifier.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:158: Warning 503: Can't wrap 'operator crpropa::EmissionMap*' unless renamed to a valid identifier.
/home/HP/CRPropa3-master/include/crpropa/Referenced.h:158: Warning 503: Can't wrap 'operator crpropa::CylindricalProjectionMap*' unless renamed to a valid identifier.
Scanning dependencies of target crpropa-swig
[ 85%] Building CXX object CMakeFiles/crpropa-swig.dir/crpropa_wrap.cxx.o
In file included from /usr/include/sys/termio.h:9:0,
                 from /usr/include/python2.7/pyport.h:663,
                 from /usr/include/python2.7/Python.h:58,
                 from /home/HP/CRPropa3-master/build/crpropa_wrap.cxx:170:
/home/HP/CRPropa3-master/include/crpropa/magneticField/PshirkovField.h:34:9: error: expected unqualified-id before numeric constant
  double B0;    // magnetic field scale
         ^
make[2]: *** [CMakeFiles/crpropa-swig.dir/build.make:133: CMakeFiles/crpropa-swig.dir/crpropa_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:213: CMakeFiles/crpropa-swig.dir/all] Error 2
make: *** [Makefile:139: all] Error 2

**Comment by DavidWalz** [comment]
This does sound like a syntax error. Is your PshirkovField.h modified with respect to the repository?

**Comment by wdtcjy** [comment]
I have similar problem here. 
[ 84%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
Linking CXX shared library libcrpropa.so
[ 84%] Built target crpropa
[ 85%] Generating crpropa_wrap.cxx
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Vector3.h:39: Warning 312: Nested union not currently supported (ignored).
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:180: Warning 361: operator! ignored
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Variant.h:98: Warning 325: Nested class not currently supported (bad_conversion ignored)
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Variant.h:203: Warning 312: Nested union not currently supported (ignored).
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/module/PropagationCK.h:50: Warning 325: Nested class not currently supported (Y ignored)
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/module/PropagationBP.h:52: Warning 325: Nested class not currently supported (Y ignored)
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/module/Output.h:27: Warning 325: Nested struct not currently supported (Property ignored)
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/ModuleList.h:29: Warning 389: operator[] ignored (consider using %extend)
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/module/ParticleCollector.h:42: Warning 389: operator[] ignored (consider using %extend)
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:176: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Grid.h:146: Warning 508: previous declaration of 'get'.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:176: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Grid.h:151: Warning 508: previous declaration of 'get'.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:176: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Grid.h:146: Warning 508: previous declaration of 'get'.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:176: Warning 508: Declaration of 'get' shadows declaration accessible via operator->(),
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Grid.h:151: Warning 508: previous declaration of 'get'.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:166: Warning 503: Can't wrap 'operator crpropa::Density*' unless renamed to a valid identifier.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:166: Warning 503: Can't wrap 'operator crpropa::Grid< crpropa::Vector3< float > >*' unless renamed to a valid identifier.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:166: Warning 503: Can't wrap 'operator crpropa::Grid< float >*' unless renamed to a valid identifier.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:166: Warning 503: Can't wrap 'operator crpropa::EmissionMap*' unless renamed to a valid identifier.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/include/crpropa/Referenced.h:166: Warning 503: Can't wrap 'operator crpropa::CylindricalProjectionMap*' unless renamed to a valid identifier.
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/python/3_repr.i:14: Warning 503: Can't wrap 'crpropa::Vector3' unless renamed to a valid identifier.
Scanning dependencies of target crpropa-swig
[ 86%] Building CXX object CMakeFiles/crpropa-swig.dir/crpropa_wrap.cxx.o
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx: In function 'PyObject* crpropa_Vector3_Sl_double_Sg____array__(crpropa::Vector3<double>*)':
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7035:5: error: 'npy_intp' was not declared in this scope
     npy_intp shape[1];
     ^~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7035:5: note: suggested alternative: 'wprintf'
     npy_intp shape[1];
     ^~~~~~~~
     wprintf
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7036:5: error: 'shape' was not declared in this scope
     shape[0] = 3;
     ^~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7036:5: note: suggested alternative: 'unshare'
     shape[0] = 3;
     ^~~~~
     unshare
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7038:34: error: 'NPY_SIZEOF_FLOAT' was not declared in this scope
     if (sizeof(self->data[0]) == NPY_SIZEOF_FLOAT)
                                  ^~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7038:34: note: suggested alternative: 'H5_SIZEOF_FLOAT'
     if (sizeof(self->data[0]) == NPY_SIZEOF_FLOAT)
                                  ^~~~~~~~~~~~~~~~
                                  H5_SIZEOF_FLOAT
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7040:48: error: 'NPY_FLOAT' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_FLOAT, self->data);
                                                ^~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7040:12: error: 'PyArray_SimpleNewFromData' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_FLOAT, self->data);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7042:39: error: 'NPY_SIZEOF_DOUBLE' was not declared in this scope
     else if (sizeof(self->data[0]) == NPY_SIZEOF_DOUBLE)
                                       ^~~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7042:39: note: suggested alternative: 'H5_SIZEOF_DOUBLE'
     else if (sizeof(self->data[0]) == NPY_SIZEOF_DOUBLE)
                                       ^~~~~~~~~~~~~~~~~
                                       H5_SIZEOF_DOUBLE
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7044:48: error: 'NPY_DOUBLE' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_DOUBLE, self->data);
                                                ^~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7044:48: note: suggested alternative: '_PC_VDISABLE'
       ro = PyArray_SimpleNewFromData(1, shape, NPY_DOUBLE, self->data);
                                                ^~~~~~~~~~
                                                _PC_VDISABLE
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7044:12: error: 'PyArray_SimpleNewFromData' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_DOUBLE, self->data);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx: In function 'PyObject* crpropa_Vector3_Sl_float_Sg____array__(crpropa::Vector3<float>*)':
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7069:5: error: 'npy_intp' was not declared in this scope
     npy_intp shape[1];
     ^~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7069:5: note: suggested alternative: 'wprintf'
     npy_intp shape[1];
     ^~~~~~~~
     wprintf
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7070:5: error: 'shape' was not declared in this scope
     shape[0] = 3;
     ^~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7070:5: note: suggested alternative: 'unshare'
     shape[0] = 3;
     ^~~~~
     unshare
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7072:34: error: 'NPY_SIZEOF_FLOAT' was not declared in this scope
     if (sizeof(self->data[0]) == NPY_SIZEOF_FLOAT)
                                  ^~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7072:34: note: suggested alternative: 'H5_SIZEOF_FLOAT'
     if (sizeof(self->data[0]) == NPY_SIZEOF_FLOAT)
                                  ^~~~~~~~~~~~~~~~
                                  H5_SIZEOF_FLOAT
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7074:48: error: 'NPY_FLOAT' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_FLOAT, self->data);
                                                ^~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7074:12: error: 'PyArray_SimpleNewFromData' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_FLOAT, self->data);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7076:39: error: 'NPY_SIZEOF_DOUBLE' was not declared in this scope
     else if (sizeof(self->data[0]) == NPY_SIZEOF_DOUBLE)
                                       ^~~~~~~~~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7076:39: note: suggested alternative: 'H5_SIZEOF_DOUBLE'
     else if (sizeof(self->data[0]) == NPY_SIZEOF_DOUBLE)
                                       ^~~~~~~~~~~~~~~~~
                                       H5_SIZEOF_DOUBLE
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7078:48: error: 'NPY_DOUBLE' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_DOUBLE, self->data);
                                                ^~~~~~~~~~
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7078:48: note: suggested alternative: '_PC_VDISABLE'
       ro = PyArray_SimpleNewFromData(1, shape, NPY_DOUBLE, self->data);
                                                ^~~~~~~~~~
                                                _PC_VDISABLE
/storage/work/y/yuj119/CRPNewVersions/CRPropa3-6/build/crpropa_wrap.cxx:7078:12: error: 'PyArray_SimpleNewFromData' was not declared in this scope
       ro = PyArray_SimpleNewFromData(1, shape, NPY_DOUBLE, self->data);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/crpropa-swig.dir/build.make:148: CMakeFiles/crpropa-swig.dir/crpropa_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/crpropa-swig.dir/all] Error 2
make: *** [Makefile:127: all] Error 2

**Comment by adundovi** [comment]
Please, open a new ticket instead of posting in closed ones. In it you should write your compiler/SWIG versions. However, at first glance, I would say that you use unsupported version of SWIG (should be 3+) to successfully compile recent versions of CRPropa.

**Comment by wdtcjy** [comment]
Sorry. I was just devastated. I am stuck at this problem for like 3 weeks. I must say installation of CRPropa is really painful. I start to use it 3 years ago. Every time I want to update its version, I feel so scary. I don't know what problem will show up. Now for this time, I first try virtual environment you recommended, but when cmake, it cannot find the swig I installed no matter what I tried(If there is a way you suggest, please let me know). Then, I tried anaconda, and conda install swig. I passed the cmake with identification of the swig 3.0.12 I installed. Then in make, this problem show up. I suspect it was because of swig. but I have no idea why. I checked every related tickets here on github and find no clue. I install crpropa on cluster. Another colleague of mine just tried and succeed...I don't see our set up any different. Our compiler is gcc 7.3.1. I have not asked him yet. Maybe he used a different swig. But my cmake shows it find the correct swig. I even tried downgraded the swig to 3.0.10 and 3.0.8, and it still cannot go through.

________________________________

**Comment by adundovi** [comment]
Don't downgrade SWIG. The problem probably lies, from what you have described, in the heterogeneity of your system: if you have many different versions of Python/SWIG/compiler present on your system, that could lead to inconsistent, somehow random results. Since, in that case, CMake finds some of the dependencies automatically, but usually not those that you want and that are needed for the successful compilation. So, either you should remove dependencies that you don't plan to use (and reduce the complexity of your system), or you should tell CMake explicitly the paths to those dependencies. Do you use Mac OS X or GNU/Linux?

**Comment by wdtcjy** [comment]
Thank you. I downgraded swig to test and recovered to 3.0.12. and I think conda install will replace and keep only one version alive. I use red hat linux. I suppose: when cmake,  it found the swig of appropriate version(3.0.12) means it will use such a version for cmake. or am I wrong? and what is the correct way to tell cmake the paths to dependencies?

When I look at the output of cmake, it looks like nothing is wrong. The swig, compiler and python all direct to the right version and path(they are found automatically). If that is the case, what happened to the make.

________________________________

**Comment by adundovi** [comment]
Remove everything from the build directory first, and then c/p here the output of the cmake command where it should be written what was exactly found. And don't forget to install `numpy` (with pip) in your python environment first.

**Comment by wdtcjy** [comment]
Really appreciate that you make me find something I missed. In the conda environment I did not install numpy. Though it shows numpy not found, but cmake goes through by that, so I never pay attention to that. I installed numpy and the error I posted went away. However, the make still failed because of the following:


[ 89%] Building CXX object CMakeFiles/testAdiabaticCooling.dir/test/testAdiabaticCooling.cpp.o
Linking CXX executable testAdiabaticCooling
libcrpropa.so: undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/testAdiabaticCooling.dir/build.make:110: testAdiabaticCooling] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/testAdiabaticCooling.dir/all] Error 2
make: *** [Makefile:127: all] Error 2

here is the cmake output after I installed numpy:

(crpropa3-6-2) [yuj119@comp-ic-0018 build]$ CMAKE_PREFIX_PATH=$CRPROPA_DIR cmake -DCMAKE_INSTALL_PREFIX=$CRPROPA_DIR ..  -DDOWNLOAD_DATA=OFF
-- The Fortran compiler identification is GNU
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working Fortran compiler: /opt/rh/devtoolset-7/root/usr/bin/gfortran
-- Check for working Fortran compiler: /opt/rh/devtoolset-7/root/usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/rh/devtoolset-7/root/usr/bin/gfortran supports Fortran 90
-- Checking whether /opt/rh/devtoolset-7/root/usr/bin/gfortran supports Fortran 90 -- yes
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/gcc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/g++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Use --as-needed linker flags!
-- Build Type: Release
-- CRPropa version: 3.1.6-21-g3a8b093 3a8b0935eae5288e34de6ffbb464153925c63c0c refs/heads/master
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
Using provided EIGEN
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Google perftools: NOT Found!
--   Include: GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND
-- FFTW3 with single precision (FFTW3F): Found!
--   Include:     /usr/include
--   Library:     /usr/lib64/libfftw3f.so
-- Quimby: NOT Found!
--   Include:     QUIMBY_INCLUDE_DIR-NOTFOUND
--   Library:     QUIMBY_LIBRARY-NOTFOUND
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23")
-- muParser: NOT Found!
--   Include:     MUPARSER_INCLUDE_DIR-NOTFOUND
--   Library:     MUPARSER_LIBRARY-NOTFOUND
-- Found ZLIB: /storage/home/yuj119/.conda/envs/crpropa3-6-2/lib/libz.so (found version "1.2.11")
-- Found HDF5: /opt/aci/sw/python/3.6.3_anaconda-5.0.1/lib/libhdf5.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;/storage/home/yuj119/.conda/envs/crpropa3-6-2/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so
-- Use absolute RPATH /storage/home/yuj119/.conda/envs/crpropa3-6-2/lib
-- Downloading of data file disabled
-- Found PythonInterp: /storage/home/yuj119/.conda/envs/crpropa3-6-2/bin/python (found version "3.8.1")
-- Found PythonLibs: /storage/home/yuj119/.conda/envs/crpropa3-6-2/lib/libpython3.8.so (found version "3.8.1")
-- Found SWIG: /storage/home/yuj119/.conda/envs/crpropa3-6-2/bin/swig (found suitable version "3.0.12", minimum required is "3.0")
-- Python: Found!
--   Version:     3.8/38
--   Executeable: /storage/home/yuj119/.conda/envs/crpropa3-6-2/bin/python
--   Include:     /storage/home/yuj119/.conda/envs/crpropa3-6-2/include/python3.8
--   Library:     /storage/home/yuj119/.conda/envs/crpropa3-6-2/lib/libpython3.8.so
--   Site-package directory: /storage/home/yuj119/.conda/envs/crpropa3-6-2/lib/python3.8/site-packages
-- Found numpy headers in /storage/home/yuj119/.conda/envs/crpropa3-6-2/lib/python3.8/site-packages/numpy/core/include
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /storage/home/yuj119/work/CRPNewVersions/CRPropa3-6/build



________________________________

**Comment by adundovi** [comment]
I see. So, the problem is now in HDF5. If you don't use this feature, run cmake to disable it: `cmake .. -DENABLE_HDF5=False`. Or, investigate why CMake didn't find the correct HDF5 path, even though it says that HDF5 has been found. I would classify this as a bug in our CMakeLists.txt or CMake itself, however, to properly debug it, the complexity of your setup should be minimized.

I do plan to rewrite the CRPropa installation manual to account these frequent issues, hence, maybe this will help in future.
