### ISSUE TITLE
Concerning DiffusionValidation.py

### ISSUE THREAD

**Issue by alexkaapa** [CRPropa/CRPropa3#114]
When running DiffusionValidtation.py from the CRPropa3-notebooks repository, an error message appears claiming that DiffusionModule is not defined. I looked at the available crpropa "commands" and, indeed, DiffusionModule was not to be found. The closest one was DiffusionSDE, but I am not sure what its function is. Anyone able to help here?

**Comment by lukasmerten** [comment]
We changed the name of the diffusion module The module DiffusionSDE is the correct module if you want to test the diffusive propagation of pseudo particles. 

This name error (DiffusionModule/DiffusionSDE) is fixed in the latest version of CRPropa3-notebooks. Just get the latest version or rename the module by hand.
