### ISSUE TITLE
power law spectrum with exponential cut-off

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#136]
The available options to specify a source includes defining a power-lax distribution in the form

`src = Source()`
`src.add(SourcePowerLawSpectrum(double Emin, double Emax, double index))`

But if, I want to add an exponential factor of the form [ exp(-E/Z) ] to the generic power law (E^a), how do I do it? Where, E & Z are energy and rigidity.

Where in the code is the functional form specified? if I change it, what changes are needed to be done elsewhere?

**Comment by rafaelab** [comment]
The shape of the cutoff is not directly implemented in CRPropa.
This can be done a posteriori when calculating the observable you want.
For example, when binning the events to obtain the energy spectrum you can give weights according to a condition e.g. exp(-E/Z) or any other functional form.

**Comment by saikat8018** [comment]
Okay, thank you for the reply.

**Comment by rafaelab** [comment]
There are multiple ways to do it.
The easiest and most flexible way is to simulate a single power law spectrum E^-1, for example, and then apply a posteriori weights according to any power law you wish. In this case the weight to be used would be E^(a_sim - a_0), where E_i is the initial energy of the cosmic ray, a_sim is the spectral index used in the simulation, and a_0 is the spectral index you are trying to achieve with the weights.
There are other ways to do it, but this way you don't have to rerun the simulation every time you want a new spectral index or cutoff shape.

**Comment by saikat8018** [comment]
One more question, I would ask before you close this issue, what is the expected runtime for a standard 4D simulation with the number of particles injected being ~10,000. And in what configuration of the computer system?

**Comment by rafaelab** [comment]
It is hard to say how long will it take because it largely depends on the specific setup: source distribution, observer size, energy range, redshift window, etc. It usually takes long (~several days running in a cluster for typical setups)

You can run simple benchmark cases for your particular application following the example available in: [https://github.com/CRPropa/CRPropa3-notebooks/tree/master/sim4D](https://github.com/CRPropa/CRPropa3-notebooks/tree/master/sim4D).

But don't be surprised if you inject 10^6 particles and only a couple of them reach the observer.

**Comment by saikat8018** [comment]
Okay. Thank you very much. I think that suffices to answer my queries, as of now. So, I am closing this issue.
