### ISSUE TITLE
Cannnot compile with the new crpropa::Variant feature

### ISSUE THREAD

**Issue by asavelie** [CRPropa/CRPropa3#146]
MacOS X Sierra, gcc-7 (from brew).

```
CRPropatest/crpropa3_source/src/module/Observer.cpp:323:29: error: conversion from 'const crpropa::Variant' to 'size_t {aka long unsigned int}' is ambiguous
    index = c->getProperty(DI);
                             ^
...

/CRPropatest/crpropa3_source/src/module/Observer.cpp:348:30: error: conversion from 'size_t {aka long unsigned int}' to 'const crpropa::Variant' is ambiguous
    c->setProperty(DI, index+1);
```

**Comment by lyang54** [comment]
Some errors for me too....

CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeTestFortranCompiler.cmake:54 (message):
  The Fortran compiler "/usr/local/bin/g77" is not able to compile a simple
  test program.

  It fails with the following output:

   Change Dir: /Users/Lili/Desktop/Google Drive/CRPropa3/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_b0888/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_b0888.dir/build.make CMakeFiles/cmTC_b0888.dir/build

  Building Fortran object CMakeFiles/cmTC_b0888.dir/testFortranCompiler.f.o

  /usr/local/bin/g77 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
  -c "/Users/Lili/Desktop/Google
  Drive/CRPropa3/build/CMakeFiles/CMakeTmp/testFortranCompiler.f" -o
  CMakeFiles/cmTC_b0888.dir/testFortranCompiler.f.o

  g77:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk:
  linker input file unused because linking not done

  Linking Fortran executable cmTC_b0888

  /usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_b0888.dir/link.txt --verbose=1

  /usr/local/bin/g77 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
  CMakeFiles/cmTC_b0888.dir/testFortranCompiler.f.o -o cmTC_b0888

  ld: library not found for -lcrt1.o

  collect2: ld returned 1 exit status

  make[1]: *** [cmTC_b0888] Error 1

  make: *** [cmTC_b0888/fast] Error 2

**Comment by rafaelab** [comment]
@lyang54 
Yours seems to be a fortran-related error. I suppose it is unrelated to this thread. I suggest you to:
1) try to use newer fortran compilers like gfortran or ifort, instead of g77; 
2) if the problem persists, report it as a separate issue.

**Comment by lyang54** [comment]
@rafaelab A very naive  question, how to force to use gfortran when building? Thanks.

**Comment by adundovi** [comment]
Use `FC` env variable. For example:
```
export FC=/usr/bin/gfortran
```
(similar like `CC` and `CXX` for C and C++ compilers, respectively).

**Comment by rafaelab** [comment]
@lyang54 
When running cmake use: 
```cmake ..  -DCMAKE_Fortran_COMPILER=/usr/bin/gfortran```
(or any other path to a fortran compiler)
Don't forget to add your other cmake flags if you have any.

**Comment by adundovi** [comment]
I tried to reproduce the reported error (crpropa::Variant) with clang 4.0.1 and gcc 7.2.1 on a Linux machine (Fedora) and I couldn't so I suspect that this is not a problem of compiler.

**Comment by adundovi** [comment]
I tried to reproduce the reported error (crpropa::Variant) with clang 4.0.1 and gcc 7.2.1 on a Linux machine (Fedora) and I couldn't so I suspect that this is not a problem of compilers.

**Comment by lyang54** [comment]
@rafaelab I didn't find gfortran in my mac version of 10.13.1, and it's saying that GNU Fortran is now provided as part of GCC. Therefore, I do "export FC=/usr/bin/gcc". It failed again with the error: 

  Run Build Command:"/usr/bin/make" "cmTC_3ddce/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_3ddce.dir/build.make CMakeFiles/cmTC_3ddce.dir/build

  Building Fortran object CMakeFiles/cmTC_3ddce.dir/testFortranCompiler.f.o

  /usr/bin/gcc -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
  -c "/Users/Lili/Desktop/Google
  Drive/CRPropa3/build/CMakeFiles/CMakeTmp/testFortranCompiler.f" -o
  CMakeFiles/cmTC_3ddce.dir/testFortranCompiler.f.o

  error: invalid value 'f95' in '-x f95'

  make[1]: *** [CMakeFiles/cmTC_3ddce.dir/testFortranCompiler.f.o] Error 1

  make: *** [cmTC_3ddce/fast] Error 2

  I will open a new issue later. thanks.

**Comment by adundovi** [comment]
@lyang54 Try to find executable `gfortran`, not `gcc`.

GCC has two meanings: one is the GNU Compiler Collection which represents many compilers, or to be more accurate frontends (like for C, C++, Fortran, Go, Ada...), and the other is an executable for GNU C compiler. If you cannot find gfortran on your Mac, try to install it with [brew](https://brew.sh/):
```
brew install gfortran
```

**Comment by TobiasWinchen** [comment]
I think my recent commit edf2f00 closes this issue. Please reopen if it still fails.

**Comment by rafaelab** [comment]
Now the compilation reaches 100% but doesn't complete. 
The same problem pops up when wrapping the code into python:

```
Softwares/CRPropa3/build/crpropa_wrap.cxx:6722:36: error: conversion from 'long' to 'const crpropa::Variant' is ambiguous
          self->setProperty(input, PyInt_AsLong(value));
                                   ^~~~~~~~~~~~~~~~~~~
```

@asavelie and @lyang54 
Has the problem been fixed for you?
