### ISSUE TITLE
Error linking with libz

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#155]
I get this error when I try to install CRPropa3-3.1 in a cluster account. What does this mean?

```
Linking CXX shared library libcrpropa.so
/usr/bin/ld: /usr/local/lib/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libz.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [libcrpropa.so] Error 1
make[1]: *** [CMakeFiles/crpropa.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by adundovi** [comment]
Zlib enables the compression of CRPropa output files. You can disable it if you don't need that feature. In your case it seems that the found zlib is compiled without -fPIC. Check if you have zlib from the distribution repository since the installation usually works with it, or compile zlib yourself and point cmake to it.

**Comment by saikat8018** [comment]
1. How do I disable zlib?

2. Else, while compiling zlib, where do I get the option to point cmake to it? Do I need to specify the CMAKE_INSTALL_PREFIX ?

**Comment by adundovi** [comment]
Dear @saikat8018, you can disable it manually by deleting or commenting those few lines in CMakeLists.txt. To make CMake finds it see [docs](https://cmake.org/cmake/help/v3.0/module/FindZLIB.html). Generally this is not a CRPropa issue and we cannot provide support for these kind of problems so I'll close the issue.
