### ISSUE TITLE
Memory problem in OMP

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#172]
When running a script with EMPairProduction(IRB) or any other electromagnetic interaction, I get the following error message: 
```
Run ModuleList
Python(19601,0x7fff9b0a3340) malloc: *** error for object 0x7ffe36d1c800: double free
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
Problem ocurring in Ubuntu 14.04 and OSX 10.13.3 when using multiple threads or multiple single-thread processes.

I believe this bug is related to (but not caused by) [this commit](https://github.com/CRPropa/CRPropa3/commit/bbbb7891ae095208b8e1e0bb0cba80ebafb07087).

**Comment by rafaelab** [comment]
Solved with [9a26c1a03644bff88cdf2b99c18673ea65d7596a](https://github.com/CRPropa/CRPropa3/commit/9a26c1a03644bff88cdf2b99c18673ea65d7596a).

**Comment by adundovi** [comment]
This is related to #166 @TobiasWinchen 
Since we need to introduce several additional checks to enable importing crpropa without data files which complicate the maintenance - maybe we should actually require the data files and revert back to a more simple code?

**Comment by rafaelab** [comment]
If the issue can be solved with a simple pragma statement, why not fix this everywhere and keep Tobias' implementation? Are there any other bugs arising from this new feature?

**Comment by adundovi** [comment]
This pragma statement should fix problems, and I hope that the feature will not cause any new troubles. But if there will be new issues due to this, CRPropa is almost useless without data files (especially the mass table) so adding additional lines and cross checks just to enable that for me is not a huge gain. Lets keep it for now, and later we will see.
