### ISSUE TITLE
Source distribution

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#186]
Suppose, I want to have a source distribution up to a certain maximum distance in a 1D simulation. I want the sources to evolve according to a redshift evolution (1+z)^m. But I want the distribution to be broken, i.e a change in the value of m at a certain value of z. Is the following a correct way to do this?

```
source = Source()
source.add(SourceRedshiftEvolution(2.0, 0.1, 2.0))
source.add(SourceRedshiftEvolution(0.0, 2.0, 4.0))
```

**Comment by rafaelab** [comment]
Hi

This is because SourceRedshiftEvolution only provides a (1+z)^m evolution. For an instance of Source(), one of the calls of SourceRedshiftEvolution would be lost, since the redshift information provided by the evolution function would be overwritten.

You can either define two different sources with different evolutions, or create your own module for a broken power law (see https://github.com/CRPropa/CRPropa3/wiki/Extending-CRPropa).

**Comment by cheiter** [comment]
Maybe an other solution is to create and process Candidates in a loop with the desired properties.
Therefore you could write a function to generate redshifts according to your broken power law model and assign them to the candidate together with the other particle properties. 

e.g. you could use something like that (the other particle properties like energy have to be specified as well):

`for i in range(0,NParticles):`
`    Redshift = SampledFromYourBrokenPowerLawModel()`
`    c = Candidate(ParticleId, Energy, PositionVector, DirectionVector, Redshift)`
`    sim.run(c)`

**Comment by saikat8018** [comment]
Thank you very much for your answer @rafaelab  and @cheiter .

But @rafaelab can you please tell me, how can I do this,

> You can either define two different sources with different evolutions ...

Because in CRPropa, if I define 2 sources in the format `source1 = Source( )` and again `source2 = Source( )`, how shall I choose the argument for `sim.run(source, 1000)`

**Comment by saikat8018** [comment]
Okay, thank you very much.
