### ISSUE TITLE
A discrepancy between using DINT and CRpropa modules

### ISSUE THREAD

**Issue by kojiishiwata** [CRPropa/CRPropa3#203]
I found a discrepancy for cosmic ray intensity (around TeV energy range) between by using DINT and by using CRPropa modules.

I attached some files to explain what I have found:
- mono_test.pdf : instruction of the simulations I tried
- ToCRpropa_18_1002.tar.gz : files for the simulation and resultant data files

In the simulation, we computed cosmic ray photons from monochromatic (1 TeV) photons and electrons distributed in light travel distance corresponding z=0 to z=5 under the CMB background. (See mono_test.pdf for detail.)

I suspect that the discrepancy is coming from the step width in distance, i.e. it is too large compared to inverse Compton scattering length.  But I'm not sure exactly. 

[ToCRpropa_18_1002.tar.gz](https://github.com/CRPropa/CRPropa3/files/2449240/ToCRpropa_18_1002.tar.gz)
[mono_test.pdf](https://github.com/CRPropa/CRPropa3/files/2449234/mono_test.pdf)

**Comment by rafaelab** [comment]
I confirm this discrepancy.
I couldn't easily spot anything wrong with the scripts.
I will investigate the issue further.

**Comment by kojiishiwata** [comment]
Dear Rafael,

Thank you for the check. (And sorry for my late response.)

At first, I thought that the discrepancy is due to 
- DINT takes into account redshift due to volume expansion, 1/(1+z)^3
- CRPropa modules such as 
sim.add(SimplePropagation(0, maxstep * Mpc))
sim.add(Redshift())
source.add(SourceRedshift1D())
do not take into account the redshift due to volume expansion (since it is 1D simulation)

But even if I took into account that, I still see discrepancy. 

That is why now I guess the discrepancy comes from DINT where propagation step is too large for low energy cosmic rays.  (But I’m not sure.)

Best wishes,

Koji

**Comment by rafaelab** [comment]
Hi,
I could not determine the exact source of the discrepancy, but since DINT's approach is completely different from CRPropa's, and because the background fields are different, I guess some difference is to be expected.
As of CRPropa 3.1.5, our latest release, we are no longer offering support for DINT. Therefore, I will close this issue.
We recommend the users to use the native CRPropa electromagnetic cascade modules (EMPairProduction, etc). We are currently working on improving the performance of these modules due to the large number of secondaries generated, but this is not yet implemented.

**Comment by kojiishiwata** [comment]
Dear Rafael,

Thank you for the updates. I understand closing this issue. I’m looking forward to the further improvements!

cheers,
Koji
