### ISSUE TITLE
CRPropa 3 Notebook 1D Simulation

### ISSUE THREAD

**Issue by josinaschulte** [CRPropa/CRPropa3#228]
In line 72 (`Z = pl.array([chargeNumber(id) for id in d['ID'].astype(int)])  # element`) of the CRPropa3 notebook 1D Simulation, I get the following error
> TypeError: in method 'chargeNumber', argument 1 of type 'int'

**Comment by TobiasWinchen** [comment]
The issue is here probably that astype(int) returns an numpy.int64 and not a standard int - depending on the installation, CRPropa might not fully support the numpy specific types. What python version and operating system are you using? 

As a quick workaraound you can convert the numpy.int64 to int via
`Z = pl.array([crpropa.chargeNumber(int(id)) for id in a.astype(int)])`

**Comment by josinaschulte** [comment]
Okay thank you, that worked. I'm using Python 3.5.3, so this might be the reason.
