### ISSUE TITLE
Hardware Requirements for Extragalactic Magnetic Fields

### ISSUE THREAD

**Issue by miguelitonieves88** [CRPropa/CRPropa3#237]
So I'm basically trying to backtrack events  all the way back to their possible origin. For this I need to superposition galactic +extragalactic magnetic fields, the galactic B field is no problem-o. 

Backtracking a particle with just the galactic magnetic field takes a few seconds, the problem is adding an extragalatic magnetic field. Mine has a a maximum radius of 300*Mpc and I'm talking about a turbulent one - perhaps the other types dolag miniati maybe less hardware demanding will try them out soon.

Regardless my computer just can't handle a vector grid for a turbulent field that big.

So I was wondering if you guys knew what kind of PC could witstand such a magnetic field or give me any pointers to figure this out.

My MacBook can't do it and a regular PC with 8GB of RAM and 4th generation CPU (I know it's old) can't either(in fact it's even worse). I can't use the school's server because it's stopped working.

Now I'm looking into buying a computer myself but I don't want to buy one that will end up being useless.

Thanks for your awesome code by the way, I'm pretty close to publishing something.

**Comment by reichherzerp** [comment]
Hi, thanks for you interest in CRPropa! 
First of all, the turbulence is generated on a periodic (or reflective), cartesian grid with N^3 grid points. Therefore, the grid size (spacing * N) is independent of your complete simulation space (your 600*Mpc).

The size of the grid depends on which fluctuations l_min < l < l_max should be present in the turbulent magnetic field:

- l_min > 2 spacing
- l_max < N*spacing/2

The correlation length also results from l_min and l_max and can be calculated in CRPropa.

In most cases it should be possible to generate a realistic turbulent field with about 1024^3 grid points. This should still be possible with your computer. If not you may test sligthly less grid points. Does this answer your Question?

Best wishes
Patrick

**Comment by miguelitonieves88** [comment]
hey bro kinda of. 

How does crpropa know that I want a magnetic field with a radius of 500* Mpc?

If I make a vector grid like this?

vgrid=VectorGrid(Vector3d(0),512,200*kpc)
initTurbulence(vgrid,8*nG,400*kpc,800*kpc,-11./3,seed)

?

Doesn't that mean that this B field only spans a cube of 512*100kpc ~ 50*mpc side? 

or are you saying that whatever i put into the grid will be repeated periodically and crpropa will automatically propagate this particle if I go beyond this distance (50*mpc), the side of the cube?

I just ran a simulation with a 512*200*kpc and it was pretty quick.

On the other hand a simulation with 512*2000kpc grid, took a hella long time ! +1 hour.

I'm trying to backtrack a particle from the 0,0,0 position to the surface of an observer sphere with ~300Mpc radius.

What's a realistic magnetic field for this?
Can you give me the set up?

Will this be good enough?
vgrid=VectorGrid(Vector3d(0),512,200*kpc)
initTurbulence(vgrid,8*nG,200*kpc,400*kpc,-11./3,seed)

How can I make it more accurate but at the same time not make it take more than an hour?

Thanks for ur help.

**Comment by adundovi** [comment]
@miguelitonieves88 please notice that employing big **turbulent** magnetic fields you suggested does not sound to be physically reasonable, thus, maybe you should re-check what kind of scenario you want to simulate. Especially since the observable Universe is highly structured at mentioned scales, so is the magnetic field, i.e., it is not homogeneously turbulent only (see for example the size of Sloan Great Wall to compare scales).

The turbulent magnetic field generator included in CRPropa always creates a cubic grid, and the maximum size of the grid is limited by the total available memory. For example, for a 1024^3 grid, you likely need 1024^3(grid points) * 3(vector) * 4 bytes(float) * 2 (the 2nd temp grid for FFT) = 24 GB. This field realization resolves at most 3 orders of magnitude in k-space. Hence, if you choose that the biggest scale is of order 500 Mpc, ~1Mpc is the smallest scale of turbulence where the field provides some power for particles (the coherence length of the field in that case is around 100 Mpc). All particles with the gyroradius below ~1 Mpc will "sense" only a non-turbulent magnetic field coming from the field interpolation, which is an effect you probably want to avoid... The question is what particle's energy you want to study?

The grid size has nothing to do with the simulation time per se. A slowdown may occur when particles propagate diffusionly as the Lorentz-force integrator has to try many step sizes until it converges. Basically, when r_g/L_c < 1, the propagation will be significantly slower than r_g/L_c > 1. Maybe this is the reason why you experience the difference in speed between two cases.

And quick explanation (for more, read the documentation):
```
vgrid=VectorGrid(Vector3d(0),512,200kpc)
initTurbulence(vgrid,8nG,400kpc,800kpc,-11./3,seed)
```
* 512 is the grid size
* 200 kpc is spacing, between grid points, usually = total box size / grid size
* 8 nG is B_rms of the field
* 400*kpc L_min (minimum value is 2*spacing)
* 800*kpc L_max (maximum value is the box size)
* CRPropa by default uses periodical boundary condition

BTW This tracker is mainly intended to report technical issues and bugs related to software - not for questions about physical scenarios that can be simulated in CRPropa.
