### ISSUE TITLE
Problem with TextOutput  Output.Event3D

### ISSUE THREAD

**Issue by JohnUSP** [CRPropa/CRPropa3#240]
Hy guys, I'm having a problem when I try to write to an output file the outcome of a 3D simulation in the format Output.Event3D. Below are the lines I'm using in my script but I also try with the notebook example in https://github.com/CRPropa/CRPropa3-notebooks/blob/master/sim4D/sim4D.v4.ipynb  getting the same result: the code seems to run properly but  the output file is empty.

obs = Observer()
obs.add(ObserverSurface(Sphere(Vector3d(0, 0, 0) * Mpc, 25 * Mpc)))
output = TextOutput('extragalactic_propagationBKol1nG_Lc1Mpc_Rs25Mpc.txt', Output.Event3D)
obs.onDetection(output)

**Comment by rafaelab** [comment]
Hi,
Without your code, I cannot try to reproduce the problem.
As for the sim4d.py script, you might be getting an empty output because the statistics is low. If this is the case, you should get some events if: you change the example to SourceDirection(Vector3d(-1,0,0)) instead of SourceIsotropicEmission() AND if you use a very low magnetic field (try, for example, with 1e-16 G).
Let me know if these tests work in the sim4d example.

**Comment by TobiasWinchen** [comment]
I assume that this issue is closed now - please reopen if I am mistaken.
