### ISSUE TITLE
error when importing crpropa with -builtin turned off

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#33]
```python
In [1]: from crpropa import *
v---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-e51e2bf39c3e> in <module>()
----> 1 from crpropa import *

/home/walz/.local/lib/python2.7/site-packages/crpropa/__init__.py in <module>()
----> 1 from crpropa import *

/home/walz/.local/lib/python2.7/site-packages/crpropa/crpropa.py in <module>()
   6788 
   6789 
-> 6790 __version__ = g_GIT_DESC
   6791 
   6792 class Vector3d(_object):

NameError: name 'g_GIT_DESC' is not defined
```

**Comment by adundovi** [comment]
Yes, I already know that and soon I will commit the fix. Actually, I didn't mean to commit this "turn off" option for the "-builtin" yet, but I've made some changes in CMake setup file unrelated to this (md5 checksum for data and optional git version embedding) while I've already started coding this "-builtin" and there are in the same file, hence I've commit the whole file. Sorry for not explicitly stating this.

The main problem is that for "turn off -builtin" we need second separated crpropa.i because there are some differences in SWIG's syntax with and without builtin. Of course, I'll try to avoid the duplication as much as possible using SWIG's %include.

**Comment by DavidWalz** [comment]
Ok. Do we need builtin to be optional? I think we should avoid complexity here by not making it optional.

**Comment by adundovi** [comment]
I thought of keeping it optional until I fix all the issues caused by it and then set it as the only option.

**Comment by rafaelab** [comment]
I'm having the same problem.
A quick work around is to comment the following lines in crpropa.i :
%pythoncode %{
    __version__ = g_GIT_DESC 
%}
Also, the flags -DENABLE_SWIG_BUILTIN=False -DENABLE_GIT=False solve the problem.

**Comment by adundovi** [comment]
Fixed for now with a default without built-in.
