### ISSUE TITLE
Add observatory exposure to lensed maps

### ISSUE THREAD

**Issue by cainaoliveira** [CRPropa/CRPropa3#347]
Hi
It is possible to weigh a particle's map (a map lensed by the galactic magnetic field) with arbitrary values? I am with an issue to add the experimental exposure to a map.

Best, 
Cainã

**Comment by rafaelab** [comment]
Hi,

If I understand correctly, your is how to get a CRPropa simulation and post-process it including your detector's specs. If that's the case you can use the lensed map or the lensed direction and directly fold in your exposure map with the simulation.  If that's the case, there is no intermediate step, it is just an operation between maps.

I will close the issue because it is not related to CRPropa.

**Comment by TobiasWinchen** [comment]
Yes - you should be able to multiply the input map by an numpy array with the weights.

**Comment by cainaoliveira** [comment]
Thanks!
