### ISSUE TITLE
more problems related to -builtin in SWIG

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#35]
For some reason, I'm getting the following error when testing the AMR support of CRPropa:  

File "../test/test-SAGA_CRPropa.py", line 20, in <module>
    bField = AMRMagneticField(field, cL, cD, cB)
TypeError: in method 'new_AMRMagneticField', argument 1 of type 'saga::ref_ptr< saga::MagneticField >'

When I compile  WITHOUT the -builtin option, it works as it did  in the past.

This is one more thing that was previously okay and stopped working after the builtin option became default. Is there an actual advantage in using it? As far as I see, it has been causing problems, and I don't see a significant performance improvement. Is this option really useful/needed? If not, I would suggest to switch back to the previous version, without builtin.

**Comment by adundovi** [comment]
I agree with you that the "built-in" is causing a lot of trouble which I didn't notice at the first place when I introduced this feature, so it would make sense to revert to the old case without the built-in, but only temporarily. Why?

Firstly, everything before was "working" because CRPropa's interface to python was tailored for the case without the built-in. If there was built-in right from the start, there would be no problem because features would be introduced and written to work with this set-up.

Secondly, SWIG developers are urging people to use this new functionality because it has many other advantages, but one above all is speed, to cite [SWIG's docs](http://www.swig.org/Doc2.0/Python.html#Python_builtin_types):

> The use of Python proxy classes has performance implications that may be unacceptable for a high-performance library. The new -builtin option instructs SWIG to forego the use of proxy classes, and instead create wrapped types as new built-in Python types. (...)
> The -builtin option provides a significant performance improvement in the wrapped code. (...)

All limitations of the built-in are manifest themselves as breaking compatibility with the old approaches and syntax, so I bet that this thing will became mandatory, default setting in the future versions of SWIG at some point and then we will be left with the legacy 3rd party library and forced to do the rewrite. Not to mention that there are already some drawbacks of extending CRPropa without it (such as that Python's usual __version__ attribute).

I'll set the default value for the built-in in the CMake configuration to "off", but I'll personally continue to use and debug the "built-in" set-up until it will be more ready and issue-free than now.

**Comment by rafaelab** [comment]
Thanks for clearing this up. I think that in the long run it might be a good option. My suggestion is to leave it optional for now, and after the public release there will be enough time to carefully test it.
