### ISSUE TITLE
Problematic definition of the spectral index in PlaneWaveTurbulence

### ISSUE THREAD

**Issue by LeanderSchlegel** [CRPropa/CRPropa3#387]
Dear all,

we noticed a problematic definition respective a bug regarding the spectral index treatment in PlaneWaveTurbulence and opened this issue to ask you if we see it correctly and formally report the issue. If we should change it, it should only be a small modification of the handling of the spectral index in the source code.

**Definition of the issue**
Using SimpleTurbulenceSpectrum just producing a powerlaw, the default value for the spectral index of 5/3. seems not to result in the expected -11/3. spectrum as shown in the following plot, that reweights the observed spectrum with +11/3. Instead the argument of -1/3. yields the -11/3. spectrum.

![spectrum](https://user-images.githubusercontent.com/32835331/149794071-2b50e6b2-94cf-40ea-94ab-f9733ecf9f5b.png)

**Minimal example to reproduce the issue**
Attached you find an example code to reproduce the plot, based on a script by @antoniusf, that generates the turbulent field, samples it onto a grid to perform a FFT gaining a spectrum that gets reweighted with +11/3.

[example.txt](https://github.com/CRPropa/CRPropa3/files/7883007/example.txt)

Thank you!

**Comment by rafaelab** [comment]
Hi @LeanderSchlegel,
Maybe @adundovi can tell a bit more about the conventions he adopted for the definition of the power spectrum.

**Comment by adundovi** [comment]
Hi @LeanderSchlegel, thanks @rafaelab,

yes, it is true that there could be a mistake in calculating the correct index, I have noticed the same in `PlaneWaveTurbulence`, but didn't have time to play around with it to double check it. The internal conversion should convert it from 5/3 to -11/3.

**Comment by antoniusf** [comment]
Hi, just a quick note from me: The problem appears to be in [`TurbulenceSpectrum::energySpectrum`](https://github.com/CRPropa/CRPropa3/blob/f790e32668edc9bee666c0029f5459d2339d84ac/include/crpropa/magneticField/turbulentField/TurbulentField.h#L80), where the energy spectrum is computed as

<img src="https://render.githubusercontent.com/render/math?math=\frac{k^q}{(1 %2b k^2) ^ { (s %2b q)/2 %2b 1}}">

This is in contrast to the formula given by Tautz and Dosch (2013), which as you know PlaveWaves is implemented after, who explicitly state that for their formula, Kolmogorov turbulence is achieved by setting s to 5/3:

<img src="https://render.githubusercontent.com/render/math?math=\frac{k^q}{(1 %2b k^2) ^ { (s %2b q)/2 }}">

Note the missing "+1" in the exponent – this explains why the correct spectral index is obtained when passing in -1/3 instead of 5/3.

While it's true that the grid turbulence models need a spectral index of 11/3 due to the way they're implemented (and this is what the extra "+1" achieves when given 5/3), the TD13 model does *not* need this extra correction and hence outputs the wrong spectrum when passed 11/3.

**Comment by adundovi** [comment]
Hmm, OK, I'll take a look how to make it consistent since the same spectrum interface should apply both, to the grid and the plane-wave methods.

**Comment by adundovi** [comment]
@antoniusf @LeanderSchlegel, O.K., I agree that we should stick to the second formula as it is a text-style definition (I also use it in my 2020 turbulence paper, Eq. 20) and add the "+1" correction in [`GridTurbulence`](https://github.com/CRPropa/CRPropa3/blob/f790e32668edc9bee666c0029f5459d2339d84ac/src/magneticField/turbulentField/GridTurbulence.cpp#L98). I am really sorry for not reviewing and replying sooner to this issue. I cannot commit the change in next few days, so if you are able, please be free to do so.

**Comment by LeanderSchlegel** [comment]
Thanks for your ok! We prepared a small fix changing the +1 and found that it would be uniform to also change the argument of energySpectrum in TurbulentField.h from khat to k, putting the multiplication with l_bendover into the function. We tested that it works and could prepare a pullrequest in the coming days :)
