### ISSUE TITLE
Error in 4D propagation simulation with PhotoPionProduction module

### ISSUE THREAD

**Issue by GDMarco** [CRPropa/CRPropa3#414]
**Describe the bug**
By running a simple CRPropa (version 3.2-37-g5364e8af) 4D simulation of propagating nuclei, an error related to the PhotoPionProduction module arises. Explicitly "error: no photon found in sampleEps, please make sure that photon field provides photons for the interaction by adapting the energy range of the tabulated photon field."   

Is the bug related to the physics in CRPropa? No

**To Reproduce**
One can simply run the example in the CRPropa documentation: https://crpropa.github.io/CRPropa3/pages/example_notebooks/sim4D/sim4D.v4.html . It is about the 4D propagation of protons.

**Expected behavior**
It is expected the simulation of the 10000 protons' propagation. However, the error stops the code very soon. 

**System (please complete the following information):**
 - Operating system: Ubuntu Linux 20.04
 - Laptop or computing cluster? Laptop
 - Python version: 3.8.10
 - Swig version: 4.0.1
 - Cmake version: 3.25.1

**Additional context**
If one rules out the processes related to the PhotoPionProduction modules (e.g. with the CMB and EBL) in the 4D propagation, the aforementioned example works.
If one keeps the PhotoPionProduction modules and rules out the ones related to the Redshift (e.g. FutureRedshift(), ObserverRedshiftWindow(), SourceRedshiftEvolution(), etc.), the simulation succeeds. 
The example works if we consider the propagation of electrons or gamma-rays.
It seems to be a conflict between the new release of the PhotoPionProduction module with the Redshift components.

**Comment by lukasmerten** [comment]
I can confirm this bug with the current master branch. I will take a closer look as soon as possible.

**Comment by JulienDoerner** [comment]
I also had a look and can confirm the bug. 

The problem is independent of the `PhotoPionProduction` but is in the behaviour of the photon field `IRB_Kneiske04` for negative redshifts. 
It seems that the photon density is set to 0 in this case, which lead to no possibility of sampling a photon from this distribution as the probability at each photon energy is 0.

In this plot I have taken the redshift scaling from the data table (blue solid) and from the photon field instance (orange, dashed). Both seems to be okay. But the photon density for a photon of $\epsilon = 0.1$ eV drops to 0 for $z< 0$. 

![redshift_scaling_density](https://user-images.githubusercontent.com/32195256/213798545-504673ea-4a22-4302-932f-090a722c2060.png)

**Comment by GDMarco** [comment]
Thanks for having a glance at that! 

I also tried to use different EBL models (Gilmore, Dominguez, Franceschini etc.), however the error rises the same.
