### ISSUE TITLE
addParticlesFromFile() doesn't work on default output

### ISSUE THREAD

**Issue by avvliet** [CRPropa/CRPropa3#45]
The lines
"
M = crpropa.ParticleMapsContainer()
wexp = -1
M.addParticlesFromFile("crpropa_output.txt", wexp)
"
do not work for the default 3D output, only if you use the TextOutput(file, "3D events") format.
It would be good if the addParticlesFromFile() function actually reads the default output or, even better, could read all outputs.

**Comment by adundovi** [comment]
I already reported this issue here: https://github.com/CRPropa/CRPropa3/issues/40 and we closed it somehow, but it seems that the issue still remains even if one puts "3D events":

* with "3D events" output is: "D   ID  E   X   Y   Z   Px  Py  Pz  ID0 E0  X0  Y0  Z0"
* ParticleMapsContainer accepts: "D, ID, ID0, E, E0, X, Y, Z, X0, Y0, Z0, Px, Py, Pz, P0x, P0y, P0z,z"

But I need to double check this...

Anyway, I wrote a script which can automatically rearrange columns of the output making it compatible with addParticlesFromFile(), here: https://github.com/adundovi/CRPropa3-scripts/blob/master/tools/output_rearrange.py

That is a quick workaround for this issue, even if you already generated the data.

**Comment by DavidWalz** [comment]
TextOutput has a somewhat flexible output.
In python it's straightforward to select columns by name (commented first line of file) using
```python
d = genfromtxt(... names=True)
d['Px'], ...
```
Either the ```addParticlesFromFile``` is given such a column awareness, or simply ```addParticle``` is used.

**Comment by DavidWalz** [comment]
If there's no better solution I will soon remove addParticleFromFile.

**Comment by adundovi** [comment]
Just for the record, one can reconstruct removed method in Python:

```pythonclass ParticleMapsContainerMod(ParticleMapsContainer):
    def addParticlesFromFile(self, filename, wexp):
        d = np.genfromtxt(filename, names=True)
        for id, en, en0, px, py, pz in zip(d['ID'], d['E'], d['E0'], d['Px'], d['Py'], d['Pz']):
            weight = pow(en0, wexp);
            self.addParticle(int(id), en*EeV, Vector3d(px, py, pz), weight)

M = crpropa.ParticleMapsContainerMod()
M.addParticlesFromFile("crpropa_output.txt", -1)
```

**Comment by TobiasWinchen** [comment]
Hi,

On Tuesday 07 June 2016 17:30:20 Andrej Dundovic wrote:
> Just for the record, one can reconstruct removed method in Python:
> 
> ```pythonclass ParticleMapsContainerMod(ParticleMapsContainer):
>     def addParticlesFromFile(self, filename, wexp):
>         d = np.genfromtxt(filename, names=True)
>         for id, en, en0, px, py, pz in zip(d['ID'], d['E'], d['E0'],
> d['Px'], d['Py'], d['Pz']): weight = pow(en0, wexp);
>             self.addParticle(int(id), en*EeV, Vector3d(px, py, pz), weight)
> 
> M = crpropa.ParticleMapsContainerMod()
> M.addParticlesFromFile("crpropa_output.txt", -1)

I would suggest to use addParticles method available in the python interface:

M.addParticles(particle_ids, energies, galactic_latitude, galactic_longitude,  
weights)

Here, the loop is done in C and thus faster. 

Cheers,


Tobi

**Comment by adundovi** [comment]
Thanks Tobias! I wasn't of this vectorized method.
