### ISSUE TITLE
How to set 'limit' parameter for EMPairProduction()

### ISSUE THREAD

**Issue by Eobard828** [CRPropa/CRPropa3#477]
I am doing an EBL simulation. My question is what the strategy is to set the 'limit' parameter for EMPairProduction(), since it seems that it has huge influence on the computational time and accuracy.

**Comment by rafaelab** [comment]
Hi @Eobard828,
As described in the documentation, this flag enables the user to control the size of the next propagation step. Since CRPropa is versatile and can simulate various processes, users should determine the value of limit based on their specific requirements, probably by running a few convergence tests themselves.
