### ISSUE TITLE
Output: beginRun() is not always called automatically

### ISSUE THREAD

**Issue by lukasmerten** [CRPropa/CRPropa3#62]
Sometimes the function Output: beginRun() is not called automatically.
I think this depends on the sim.run() arguments. For sim.run(source) it works, for sim.run(Candidate) not.

See the example notebook "3D trajectories in a turbulent field" of the wiki page. 
This notebook ends with the error message "Output: call beginRun before using Output", when the typo Bfield instead of BField is fixed.
This error can be fixed with a replacement of 
'sim.add(TextOutput('trajectories.txt', Output.Trajectory3D))'
through
'Out = TextOutput('trajectories.txt', Output.Trajectory3D)
Out.beginRun()
sim.add(Out)'
But I don't think that this is the intended behavior.

Best, Lukas

**Comment by DavidWalz** [comment]
Thanks! Both fixed.

**Comment by geromueller** [comment]
Hi,
yes, this had to come up at some point.. I did not add begin/endRun to .run(Candidate) as this function is often called multiple times in a loop.
We are in a dilemma, as we introduced endRun to close/flush the output files, so they could be read after calling run.
But, this introduces more problems: ROOT files, gzipped Text files and HDF5 files need to be closed, not only flushed. So endRun may only be called once atm.
We did all this, so the user does not need to call .close() on the files.
I now think there is no way to avoid this explicit call.
Any othe ideas/optinions? Oherwise, i refactor all Output modules, so that begin/endRun may be called multiple times.
Gero

**Comment by DavidWalz** [comment]
Hi Gero,
I moved the functionality of run(Candidate) to processToFinish, (for lack of a better name).
This is simply to make all overloaded run functions behave the same way.
I personally consider a script as advanced, if it calls processToFinish (formerly run) inside a loop. Therefore I find it ok if we require the user call beginRun and endRun by himself and see no need for further action, because nothing changed compared to the situation before.
However, I wouldn't object to a refactoring of the Output modules begin/endRun :)

**Comment by DavidWalz** [comment]
So after discussing, Gero and I are thinking about removing the beginRun/endRun formalism.
Currently the only important use case is the flushing/closing of output after the simulation completes, but before the simulation script terminates. Thus, we can get rid of begin/endRun by requiring the user to explicitly call output.close() in these special cases.
Any thoughts or objections?

**Comment by adundovi** [comment]
I agree with abandoning automatic beginRun/endRun inside run() and requiring explicit init() and close/finish(). In several occasions I needed to override begin/endRun and at the same time I wanted to continue using fast cpp run() loop, but I couldn't decouple those two because begin/endRun are called inside run().

For example, loading magnetic fields takes some time and one would like to run different set-ups on the same field in the same steering card. To avoid loading fields for every iteration, one would call init() only on those modules which have changing properties through iterations.

Maybe, to keep the old, more simple behaviour, we could provide python wrapper around ModuleList() which would be a shortcut method for those three lines:
```
m.init()
m.run()
m.close()
```

But generally I think that run() should be a "stateless" method.

**Comment by adundovi** [comment]
Now I see that I've mixed up init() and beginRun() in the given example for fields, but this doesn't change the argument that run() shouldn't change the general state of modules. The bottom line would be that it should be possible to call run() several times in a row without an additional preparation.

**Comment by geromueller** [comment]
Removed begin/endRun in  d9cf64f
